app/solicitacao/urls.py
from django.urls import include, path
from . import views as solicitacao

app_name = 'solicitacao'

urlpatterns = [
    path('', solicitacao.Home.as_view(), name = 'home'),
    # adição
    path('nova/solicitacao/motorista/', solicitacao.AddMotorista.as_view(), name = 'add-motorista'),
    path('nova/solicitacao/pedreiro/', solicitacao.AddPedreiro.as_view(), name = 'add-pedreiro'),
    path('nova/solicitacao/cozinheiro/', solicitacao.AddCozinheiro.as_view(), name = 'add-cozinheiro'),
    path('nova/solicitacao/professor/', solicitacao.AddProfessor.as_view(), name = 'add-professor'),
    # listagem adm
    path('lista/solicitacoes/motorista/', solicitacao.AdmMotorista.as_view(), name='adm-motorista'),
    path('lista/solicitacoes/pedreiro/', solicitacao.AdmPedreiro.as_view(), name='adm-pedreiro'),
    path('lista/solicitacoes/cozinheiro/', solicitacao.AdmCozinheiro.as_view(), name='adm-cozinheiro'),
    path('lista/solicitacoes/professor/', solicitacao.AdmProfessor.as_view(), name='adm-professor'),
    # listagem user
    path('lista/minhas/solicitacoes/motorista/', solicitacao.UserMotorista.as_view(), name='user-motorista'),
    path('lista/minhas/solicitacoes/pedreiro/', solicitacao.UserPedreiro.as_view(), name='user-pedreiro'),
    path('lista/minhas/solicitacoes/cozinheiro/', solicitacao.UserCozinheiro.as_view(), name='user-cozinheiro'),
    path('lista/minhas/solicitacoes/professor/', solicitacao.UserProfessor.as_view(), name='user-professor'),
    # visualizar solicitacao
    path('visualizar/solicitacao/<pk>/', solicitacao.Visualizar.as_view(), name = 'visualizar')
]

hub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # solicitacao
    path('', include('app.solicitacao.urls'), name='solicitacao'),
    # core
    path('', include('app.core.urls'), name='core')
]

app/solicitacao/models.py
from django.db import models
from app.core.models import UUIDUser, CreateUpdateModel

class Motorista(CreateUpdateModel):
    user = models.ForeignKey(UUIDUser, on_delete = models.CASCADE, related_name = 'users', verbose_name = 'Usuário')
    endereco = models.TextField(verbose_name = 'Endereço')
    data = models.DateField(verbose_name = 'Data')
    hora = models.TimeField(verbose_name = 'Hora')
    solicitacao = models.DateTimeField(verbose_name = 'Data da Solicitação', auto_now_add = True)

    def __str__(self):
        return 'Corrida de %s' % self.user.first_name

class Pedreiro(CreateUpdateModel):
    user = models.ForeignKey(UUIDUser, on_delete = models.CASCADE, related_name = 'user', verbose_name = 'Usuário')
    descricao = models.TextField(verbose_name = 'Descrição do Serviço')
    solicitacao = models.DateTimeField(verbose_name = 'Data da Solicitação', auto_now_add = True)

    def __str__(self):
        return 'Solicitação de %s' % self.user.first_name

class Professor(CreateUpdateModel):
    user = models.ForeignKey(UUIDUser, on_delete = models.CASCADE, related_name = 'use', verbose_name = 'Usuário')
    materia = models.CharField(max_length = 100, verbose_name = 'Matéria')
    descricao = models.TextField(verbose_name = 'Descrição do Problema')
    solicitacao = models.DateTimeField(verbose_name = 'Data da Solicitação', auto_now_add = True)

    def __str__(self):
        return 'Aula de %s' % self.user.first_name

class Cozinheiro(CreateUpdateModel):
    user = models.ForeignKey(UUIDUser, on_delete = models.CASCADE, related_name = 'usuario', verbose_name = 'Usuário')
    descricao = models.TextField(verbose_name = 'Descrição da Refeição')
    solicitacao = models.DateTimeField(verbose_name = 'Data da Solicitação', auto_now_add = True)

    def __str__(self):
        return 'Refeição de %s' % self.user.first_name

app/solicitacao/forms.py
from django import forms

from .models import *

class AddMotoristaForm(forms.ModelForm):
  
  class Meta:
    model = Motorista
    fields = ('endereco', 'data', 'hora')
    labels = {
    	'endereco': 'Endereço',
    	'data': 'Data',
    	'hora': 'Hora',
    }
    widgets = {
      'data': forms.DateInput(),
      'hora': forms.TimeInput(),
      'endereco': forms.TextInput(),
    }

class AddPedreiroForm(forms.ModelForm):
  
  class Meta:
    model = Pedreiro
    fields = ('descricao',)
    labels = {
    	'descricao': 'Descrição',
    }
    widgets = {
      'descricao': forms.TextInput(),
    }

class AddProfessorForm(forms.ModelForm):
  
  class Meta:
    model = Professor
    fields = ('materia', 'descricao')
    labels = {
    	'materia': 'Matéria',
    	'descricao': 'Descrição',
    }
    widgets = {
      'descricao': forms.TextInput(),
    }

class AddCozinheiroForm(forms.ModelForm):
  
  class Meta:
    model = Cozinheiro
    fields = ('descricao',)
    labels = {
    	'descricao': 'Descrição',
    }
    widgets = {
      'descricao': forms.TextInput(),
    }

app/solicitacao/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import *
from .forms import *

class Home(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'solicitacao/index.html')

class AddMotorista(CreateView):
    model = Motorista
    template_name = 'solicitacao/solicitacoes/add-solicitacao.html'
    success_url = reverse_lazy('solicitacao:home')
    form_class = AddMotoristaForm

    def form_valid(self, form):
    	obj = form.save(commit=False)
    	obj.user = self.request.user
    	obj.save()
    	return super(AddMotorista, self).form_valid(form)

class AddCozinheiro(CreateView):
    model = Cozinheiro
    template_name = 'solicitacao/solicitacoes/add-solicitacao.html'
    success_url = reverse_lazy('solicitacao:home')
    form_class = AddCozinheiroForm

    def form_valid(self, form):
    	obj = form.save(commit=False)
    	obj.user = self.request.user
    	obj.save()
    	return super(AddCozinheiro, self).form_valid(form)

class AddProfessor(CreateView):
    model = Professor
    template_name = 'solicitacao/solicitacoes/add-solicitacao.html'
    success_url = reverse_lazy('solicitacao:home')
    form_class = AddProfessorForm

    def form_valid(self, form):
    	obj = form.save(commit=False)
    	obj.user = self.request.user
    	obj.save()
    	return super(AddProfessor, self).form_valid(form)

class AddPedreiro(CreateView):
    model = Pedreiro
    template_name = 'solicitacao/solicitacoes/add-solicitacao.html'
    success_url = reverse_lazy('solicitacao:home')
    form_class = AddPedreiroForm

    def form_valid(self, form):
    	obj = form.save(commit=False)
    	obj.user = self.request.user
    	obj.save()
    	return super(AddPedreiro, self).form_valid(form)

class AdmMotorista(ListView):
    model = Motorista
    template_name = 'solicitacao/solicitacoes/listagem.html'
    def get_context_data(self, **kwargs):
        kwargs['object_list'] = Motorista.objects.all().order_by('-solicitacao')
        return super(AdmMotorista, self).get_context_data(**kwargs)

class AdmProfessor(ListView):
    model = Professor
    template_name = 'solicitacao/solicitacoes/listagem.html'
    def get_context_data(self, **kwargs):
        kwargs['object_list'] = Professor.objects.all().order_by('-solicitacao')
        return super(AdmProfessor, self).get_context_data(**kwargs)

class AdmPedreiro(ListView):
    model = Pedreiro
    template_name = 'solicitacao/solicitacoes/listagem.html'
    def get_context_data(self, **kwargs):
        kwargs['object_list'] = Pedreiro.objects.all().order_by('-solicitacao')
        return super(AdmPedreiro, self).get_context_data(**kwargs)

class AdmCozinheiro(ListView):
    model = Cozinheiro
    template_name = 'solicitacao/solicitacoes/listagem.html'
    def get_context_data(self, **kwargs):
        kwargs['object_list'] = Cozinheiro.objects.all().order_by('-solicitacao')
        return super(AdmCozinheiro, self).get_context_data(**kwargs)

class UserMotorista(ListView):
    model = Motorista
    template_name = 'solicitacao/solicitacoes/listagem.html'
    def get_context_data(self, **kwargs):
        kwargs['object_list'] = Motorista.objects.filter(user = self.request.user).order_by('-solicitacao')
        return super(UserMotorista, self).get_context_data(**kwargs)

class UserProfessor(ListView):
    model = Professor
    template_name = 'solicitacao/solicitacoes/listagem.html'
    def get_context_data(self, **kwargs):
        kwargs['object_list'] = Professor.objects.filter(user = self.request.user).order_by('-solicitacao')
        return super(UserProfessor, self).get_context_data(**kwargs)

class UserPedreiro(ListView):
    model = Pedreiro
    template_name = 'solicitacao/solicitacoes/listagem.html'
    def get_context_data(self, **kwargs):
        kwargs['object_list'] = Pedreiro.objects.filter(user = self.request.user).order_by('-solicitacao')
        return super(UserPedreiro, self).get_context_data(**kwargs)

class UserCozinheiro(ListView):
    model = Cozinheiro
    template_name = 'solicitacao/solicitacoes/listagem.html'
    def get_context_data(self, **kwargs):
        kwargs['object_list'] = Cozinheiro.objects.filter(user = self.request.user).order_by('-solicitacao')
        return super(UserCozinheiro, self).get_context_data(**kwargs)

class Visualizar(View):
    def get(self, request, pk):
        cozinha = Cozinheiro.objects.filter(id = pk).first()
        pedreiro = Pedreiro.objects.filter(id = pk).first()
        motorista = Motorista.objects.filter(id = pk).first()
        professor = Professor.objects.filter(id = pk).first()
        if cozinha != None:
            return render(request, 'solicitacao/solicitacoes/visualizar.html', {'object': cozinha})
        elif pedreiro != None:
            return render(request, 'solicitacao/solicitacoes/visualizar.html', {'object': pedreiro})
        elif motorista != None:
            return render(request, 'solicitacao/solicitacoes/visualizar.html', {'object': motorista})
        else:
            return render(request, 'solicitacao/solicitacoes/visualizar.html', {'object': professor})

templates/solicitacao/solicitacoes/add-solicitacao.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<title>Sistema de Votação | Cadastro</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %} ">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">
				<form class="login100-form validate-form flex-sb flex-w" method="post">
					{% csrf_token %}
					<span class="login100-form-title p-b-32">
						Nova Solicitação
					</span>
					{% for field in form.visible_fields %}
		          	<span class="txt1 p-b-11">
		          		{{ field.label }}
		          	</span>
		            <div class="wrap-input100 validate-input m-b-36">
		                {{ field|add_class:'input100' }}
		                <span class="focus-input100"></span>
		                {% for error in field.errors %}
		                  <span class="help-block">{{ error }}</span>
		                {% endfor %}
		              </div>
		          {% endfor %}
					<div class="container-login100-form-btn">
						<button class="login100-form-btn" type="submit">Adicionar</button>
					</div>

				</form>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

templates/solicitacao/solicitacoes/listagem.html
{% extends '../base.html' %}
{% block content %}

    <div class="col-md-8">

        {% for object in object_list %}

          <!-- Blog Post -->
          <div class="card mb-4">
            <div class="card-body">
              <h2 class="card-title">{{ object }}</h2>
              <a href="{% url 'solicitacao:visualizar' object.pk %}" class="btn btn-primary">Visualizar &rarr;</a>
            </div>
            <div class="card-footer text-muted">
              {{ object.solicitacao|date }} por
              {{ object.user.first_name }}
            </div>
          </div>

        {% endfor %}

    </div>

{% endblock %}

templates/solicitacao/solicitacoes/visualizar.html
{% extends '../base.html' %}
{% block content %}

        <!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Title -->
          <h1 class="mt-4">{{ object }}</h1>

          <!-- Author -->
          <p class="lead">
            Solicitado por {{ object.user.username }}
          </p>

          <hr>

          <!-- Date/Time -->
          <p> {{object.solicitacao}} </p>

          <hr>
          <!-- Post Content -->
          <p class="lead">{{ object.endereco }}</p>
          <p class="lead">{{ object.materia }}</p>
          <p class="lead">{{ object.descricao }}</p>
          <p class="lead">{{ object.data }}</p>
          <p class="lead">{{ object.hora }}</p>
          <hr>

        </div>

{% endblock %}