app/core/urls.py
from django.urls import include, path
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views

from . import views as core

app_name = 'core'

urlpatterns = [
	path('login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),
	path('cadastro', core.UserCreateView.as_view(), name='cadastro'),
]

app/solicitacao/urls.py
from django.urls import include, path
from . import views as solicitacao

app_name = 'solicitacao'

urlpatterns = [
    path('', solicitacao.Home.as_view(), name = 'home'),
    # adição
    path('nova/solicitacao/motorista/', solicitacao.AddMotorista.as_view(), name = 'add-motorista'),
    path('nova/solicitacao/pedreiro/', solicitacao.AddPedreiro.as_view(), name = 'add-pedreiro'),
    path('nova/solicitacao/cozinheiro/', solicitacao.AddCozinheiro.as_view(), name = 'add-cozinheiro'),
    path('nova/solicitacao/professor/', solicitacao.AddProfessor.as_view(), name = 'add-professor'),
    # listagem adm
    path('lista/solicitacoes/motorista/', solicitacao.AdmMotorista.as_view(), name='adm-motorista'),
    path('lista/solicitacoes/pedreiro/', solicitacao.AdmPedreiro.as_view(), name='adm-pedreiro'),
    path('lista/solicitacoes/cozinheiro/', solicitacao.AdmCozinheiro.as_view(), name='adm-cozinheiro'),
    path('lista/solicitacoes/professor/', solicitacao.AdmProfessor.as_view(), name='adm-professor'),
    # listagem user
    path('lista/minhas/solicitacoes/motorista/', solicitacao.UserMotorista.as_view(), name='user-motorista'),
    path('lista/minhas/solicitacoes/pedreiro/', solicitacao.UserPedreiro.as_view(), name='user-pedreiro'),
    path('lista/minhas/solicitacoes/cozinheiro/', solicitacao.UserCozinheiro.as_view(), name='user-cozinheiro'),
    path('lista/minhas/solicitacoes/professor/', solicitacao.UserProfessor.as_view(), name='user-professor'),
    # visualizar solicitacao
    path('visualizar/solicitacao/<pk>/', solicitacao.Visualizar.as_view(), name = 'visualizar')
]

hub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # solicitacao
    path('', include('app.solicitacao.urls'), name='solicitacao'),
    # core
    path('', include('app.core.urls'), name='core')
]

app/solicitacao/models.py
from django.db import models
from app.core.models import UUIDUser, CreateUpdateModel

class Motorista(CreateUpdateModel):
    user = models.ForeignKey(UUIDUser, on_delete = models.CASCADE, related_name = 'users', verbose_name = 'Usuário')
    endereco = models.TextField(verbose_name = 'Endereço')
    data = models.DateField(verbose_name = 'Data')
    hora = models.TimeField(verbose_name = 'Hora')
    solicitacao = models.DateTimeField(verbose_name = 'Data da Solicitação', auto_now_add = True)

    def __str__(self):
        return 'Corrida de %s' % self.user.first_name

class Pedreiro(CreateUpdateModel):
    user = models.ForeignKey(UUIDUser, on_delete = models.CASCADE, related_name = 'user', verbose_name = 'Usuário')
    descricao = models.TextField(verbose_name = 'Descrição do Serviço')
    solicitacao = models.DateTimeField(verbose_name = 'Data da Solicitação', auto_now_add = True)

    def __str__(self):
        return 'Solicitação de %s' % self.user.first_name

class Professor(CreateUpdateModel):
    user = models.ForeignKey(UUIDUser, on_delete = models.CASCADE, related_name = 'use', verbose_name = 'Usuário')
    materia = models.CharField(max_length = 100, verbose_name = 'Matéria')
    descricao = models.TextField(verbose_name = 'Descrição do Problema')
    solicitacao = models.DateTimeField(verbose_name = 'Data da Solicitação', auto_now_add = True)

    def __str__(self):
        return 'Aula de %s' % self.user.first_name

class Cozinheiro(CreateUpdateModel):
    user = models.ForeignKey(UUIDUser, on_delete = models.CASCADE, related_name = 'usuario', verbose_name = 'Usuário')
    descricao = models.TextField(verbose_name = 'Descrição da Refeição')
    solicitacao = models.DateTimeField(verbose_name = 'Data da Solicitação', auto_now_add = True)

    def __str__(self):
        return 'Refeição de %s' % self.user.first_name

app/solicitacao/forms.py
from django import forms

from .models import *

class AddMotoristaForm(forms.ModelForm):
  
  class Meta:
    model = Motorista
    fields = ('endereco', 'data', 'hora')
    labels = {
    	'endereco': 'Endereço',
    	'data': 'Data',
    	'hora': 'Hora',
    }
    widgets = {
      'data': forms.DateInput(),
      'hora': forms.TimeInput(),
      'endereco': forms.TextInput(),
    }

class AddPedreiroForm(forms.ModelForm):
  
  class Meta:
    model = Pedreiro
    fields = ('descricao',)
    labels = {
    	'descricao': 'Descrição',
    }
    widgets = {
      'descricao': forms.TextInput(),
    }

class AddProfessorForm(forms.ModelForm):
  
  class Meta:
    model = Professor
    fields = ('materia', 'descricao')
    labels = {
    	'materia': 'Matéria',
    	'descricao': 'Descrição',
    }
    widgets = {
      'descricao': forms.TextInput(),
    }

class AddCozinheiroForm(forms.ModelForm):
  
  class Meta:
    model = Cozinheiro
    fields = ('descricao',)
    labels = {
    	'descricao': 'Descrição',
    }
    widgets = {
      'descricao': forms.TextInput(),
    }

app/solicitacao/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import *
from .forms import *

class Home(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'solicitacao/index.html')

class AddMotorista(CreateView):
    model = Motorista
    template_name = 'solicitacao/solicitacoes/add-solicitacao.html'
    success_url = reverse_lazy('solicitacao:home')
    form_class = AddMotoristaForm

    def form_valid(self, form):
    	obj = form.save(commit=False)
    	obj.user = self.request.user
    	obj.save()
    	return super(AddMotorista, self).form_valid(form)

class AddCozinheiro(CreateView):
    model = Cozinheiro
    template_name = 'solicitacao/solicitacoes/add-solicitacao.html'
    success_url = reverse_lazy('solicitacao:home')
    form_class = AddCozinheiroForm

    def form_valid(self, form):
    	obj = form.save(commit=False)
    	obj.user = self.request.user
    	obj.save()
    	return super(AddCozinheiro, self).form_valid(form)

class AddProfessor(CreateView):
    model = Professor
    template_name = 'solicitacao/solicitacoes/add-solicitacao.html'
    success_url = reverse_lazy('solicitacao:home')
    form_class = AddProfessorForm

    def form_valid(self, form):
    	obj = form.save(commit=False)
    	obj.user = self.request.user
    	obj.save()
    	return super(AddProfessor, self).form_valid(form)

class AddPedreiro(CreateView):
    model = Pedreiro
    template_name = 'solicitacao/solicitacoes/add-solicitacao.html'
    success_url = reverse_lazy('solicitacao:home')
    form_class = AddPedreiroForm

    def form_valid(self, form):
    	obj = form.save(commit=False)
    	obj.user = self.request.user
    	obj.save()
    	return super(AddPedreiro, self).form_valid(form)

class AdmMotorista(ListView):
    model = Motorista
    template_name = 'solicitacao/solicitacoes/listagem.html'
    def get_context_data(self, **kwargs):
        kwargs['object_list'] = Motorista.objects.all().order_by('-solicitacao')
        return super(AdmMotorista, self).get_context_data(**kwargs)

class AdmProfessor(ListView):
    model = Professor
    template_name = 'solicitacao/solicitacoes/listagem.html'
    def get_context_data(self, **kwargs):
        kwargs['object_list'] = Professor.objects.all().order_by('-solicitacao')
        return super(AdmProfessor, self).get_context_data(**kwargs)

class AdmPedreiro(ListView):
    model = Pedreiro
    template_name = 'solicitacao/solicitacoes/listagem.html'
    def get_context_data(self, **kwargs):
        kwargs['object_list'] = Pedreiro.objects.all().order_by('-solicitacao')
        return super(AdmPedreiro, self).get_context_data(**kwargs)

class AdmCozinheiro(ListView):
    model = Cozinheiro
    template_name = 'solicitacao/solicitacoes/listagem.html'
    def get_context_data(self, **kwargs):
        kwargs['object_list'] = Cozinheiro.objects.all().order_by('-solicitacao')
        return super(AdmCozinheiro, self).get_context_data(**kwargs)

class UserMotorista(ListView):
    model = Motorista
    template_name = 'solicitacao/solicitacoes/listagem.html'
    def get_context_data(self, **kwargs):
        kwargs['object_list'] = Motorista.objects.filter(user = self.request.user).order_by('-solicitacao')
        return super(UserMotorista, self).get_context_data(**kwargs)

class UserProfessor(ListView):
    model = Professor
    template_name = 'solicitacao/solicitacoes/listagem.html'
    def get_context_data(self, **kwargs):
        kwargs['object_list'] = Professor.objects.filter(user = self.request.user).order_by('-solicitacao')
        return super(UserProfessor, self).get_context_data(**kwargs)

class UserPedreiro(ListView):
    model = Pedreiro
    template_name = 'solicitacao/solicitacoes/listagem.html'
    def get_context_data(self, **kwargs):
        kwargs['object_list'] = Pedreiro.objects.filter(user = self.request.user).order_by('-solicitacao')
        return super(UserPedreiro, self).get_context_data(**kwargs)

class UserCozinheiro(ListView):
    model = Cozinheiro
    template_name = 'solicitacao/solicitacoes/listagem.html'
    def get_context_data(self, **kwargs):
        kwargs['object_list'] = Cozinheiro.objects.filter(user = self.request.user).order_by('-solicitacao')
        return super(UserCozinheiro, self).get_context_data(**kwargs)

class Visualizar(View):
    def get(self, request, pk):
        cozinha = Cozinheiro.objects.filter(id = pk).first()
        pedreiro = Pedreiro.objects.filter(id = pk).first()
        motorista = Motorista.objects.filter(id = pk).first()
        professor = Professor.objects.filter(id = pk).first()
        if cozinha != None:
            return render(request, 'solicitacao/solicitacoes/visualizar.html', {'object': cozinha})
        elif pedreiro != None:
            return render(request, 'solicitacao/solicitacoes/visualizar.html', {'object': pedreiro})
        elif motorista != None:
            return render(request, 'solicitacao/solicitacoes/visualizar.html', {'object': motorista})
        else:
            return render(request, 'solicitacao/solicitacoes/visualizar.html', {'object': professor})

templates/solicitacao/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Sistema de Serviços Terceirizados | Home</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/blog-home.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="{% url 'solicitacao:home' %}">Sistema de Serviços Terceirizados</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'solicitacao:home' %}"><i class="fas fa-home"></i> Home</a>
            </li>
            {% if request.user.is_authenticated %}
            <li>
              <a href="" class="nav-link"><i class="fas fa-user-alt"></i> {{ request.user.username }}</a>
            </li>
            <li>
              <a href="{% url 'core:logout' %}" class="nav-link"><i class="fas fa-sign-out-alt"></i> Sair</a>
            </li>
            {% else %}
            <li>
              <a href="{% url 'core:login' %}" class="nav-link"><i class="fas fa-sign-in-alt"></i> Login</a>
            </li>
            <li>
              <a href="{% url 'core:cadastro' %}" class="nav-link"><i class="fas fa-user-alt"></i> Cadastro</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

        <!-- Page Content -->
        <div class="container">

          <div class="row">

    {% block content %}

    {% endblock %}

    <!-- Sidebar Widgets Column -->
    <div class="col-md-4">

      {% if request.user.is_staff %}
      <div class="card my-4">
        <h5 class="card-header">Solicitações Por Categoria</h5>
        <div class="card-body">
          <ul>
            <li><a href="{% url 'solicitacao:adm-motorista' %}">Motorista</a></li>
            <li><a href="{% url 'solicitacao:adm-pedreiro' %}">Pedreiro</a></li>
            <li><a href="{% url 'solicitacao:adm-professor' %}">Professor</a></li>
            <li><a href="{% url 'solicitacao:adm-cozinheiro' %}">Cozinheiro</a></li>
          </ul>
        </div>
      </div>
      {% else %}
      <!-- Side Widget -->
      <div class="card my-4">
        <h5 class="card-header">Minhas Solicitações</h5>
        <div class="card-body">
          <ul>
            <li><a href="{% url 'solicitacao:user-motorista' %}">Motorista</a></li>
            <li><a href="{% url 'solicitacao:user-pedreiro' %}">Pedreiro</a></li>
            <li><a href="{% url 'solicitacao:user-professor' %}">Professor</a></li>
            <li><a href="{% url 'solicitacao:user-cozinheiro' %}">Cozinheiro</a></li>
          </ul>
        </div>
      </div>

      <!-- Side Widget -->
      <div class="card my-4">
        <h5 class="card-header">Nova Solicitação</h5>
        <div class="card-body">
          <ul>
            <li><a href="{% url 'solicitacao:add-motorista' %}">Motorista</a></li>
            <li><a href="{% url 'solicitacao:add-pedreiro' %}">Pedreiro</a></li>
            <li><a href="{% url 'solicitacao:add-professor' %}">Professor</a></li>
            <li><a href="{% url 'solicitacao:add-cozinheiro' %}">Cozinheiro</a></li>
          </ul>
        </div>
      </div>
      {% endif %}

    </div>

  </div>
  <!-- /.row -->

</div>
<!-- /.container -->
    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Sistema de Serviços Terceirizados 2019</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

</html>

templates/solicitacao/index.html
{% extends './base.html' %}

{% block content %}

        <!-- Blog Entries Column -->
        <div class="col-md-8">

          <h1 class="my-4">Bem vindo(a), {{request.user.first_name}}</h1>          

        </div>

{% endblock %}